version: "3.9"
services:
  postgres:
    restart: always
    image: postgres:14.1
    environment:
      POSTGRES_DB: 'studentapidb'
      POSTGRES_USER: 'api'
      POSTGRES_PASSWORD: 'apipassword'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    restart: always
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      DB_USER: 'api'
      DB_PASSWORD: 'apipassword'
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_SCHEMA: 'studentapidb'
    links:
      - postgres